name: Artifact Demo

on: push

jobs:
  job_1:
    name: Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: "Create local file"
        run: echo "workflow ile oluşturulan bir dosyayım.">file.txt
      - uses: actions/upload-artifact@v4
        with:
          name: file
          path: file.txt

  job_2:
    name: Download artifact
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: file
      - run: cat file.txt
      
