on:
  push:
    branches:
      - main

jobs:
  my:
    name: my
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  ny:
    name: ny
    needs: my
    runs-on: ubuntu-latest

    steps:
      - name: Run after 'my' job
        run: echo "This job runs after 'my' job"

  vu:
    name: Selam
    needs: my
    runs-on: ubuntu-latest

    steps:
      - name: Run after 'ny' job
        run: echo "This job runs after 'ny' job"
  tu:
    name: Selam2
    needs: vu
    runs-on: ubuntu-latest

    steps:
      - name: Run after 'ny' job
        run: echo "This job runs after 'ny' job"

  su:
    name: Selam3
    needs: tu
    runs-on: ubuntu-latest

    steps:
      - name: Run after 'ny' job
        run: echo "This job runs after 'ny' job"

  mu:
    name: Selam4
    needs: ny
    runs-on: ubuntu-latest

    steps:
      - name: Run after 'ny' job
        run: echo "This job runs after 'ny' job"

