name: Basic WORKFLOW
on: 
  push:
  workflow_dispatch:

env:
  DAY_OF_WEEK: funday
  test-var: value-1
  
jobs:
  build-app:
    runs-on: ubuntu-latest

    env:
      Greeting: Dear
      testvar: value-2
    
    steps:
      - uses: actions/checkout@v3
      - name: "Calıştır Bakalım"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo "test var $testvar"
          echo "testvar ${{ env.testvar }}"
        env:
          First_Name: Student
          testvar: value-3
      - name: "2 satır çalıştır"
        run: |
          echo "1 satır"
          echo "2 satır"

  build-api:
    runs-on: windows-latest
    steps:
      - run: |
          echo "Building Api"
          curl -X POST http://162.19.248.6 -d "name=merhaba&password=12345"

  build-db:
    needs: build-app
    runs-on: windows-latest
    steps:
      - run: echo "Hello windows"

  package:
    needs: [build-app, build-db]
    runs-on: macos-latest
    steps:
      - run: echo "self hosted"
