name: PHP CI

on:
  push:
    branches:
      - main  # Run on push to main branch
  pull_request:
    branches:
      - main  # Run on pull request targeting main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest version of Ubuntu
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Specify PHP version, e.g., 7.4 or 8.0

      # Install Composer
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      # Install dependencies
      - name: Install dependencies
        run: |
          ls -al
          cd ./myapphp
          composer install --no-interaction 

      # Run tests (using PHPUnit as an example)
      - name: Run tests
        run: |
          cd ./myapphp
          vendor/bin/phpunit --coverage-text /myapphp

      # Optionally: Run linting (PHP_CodeSniffer)
      - name: Run PHP CodeSniffer
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          phpcs --standard=PSR12 /myapphp/src/

      # Optionally: Run static analysis (PHPStan)
      - name: Run PHPStan
        run: |
          composer require --dev phpstan/phpstan /myapphp
          vendor/bin/phpstan analyse /myapphp/src/
